/*
 * BREAKTHROUGH 2.0
 * (C) G.Dar 1987-2023 :) !
 * (portions inspired by Windows, since 1990)
 * 
 * http://nano-x.org/ ahah siete morti :D https://github.com/moovel/microwindows
 * https://minigui.fmsoft.cn/api_ref/3.0.12_threads/index.html boh...?
 */
 
#include <xc.h>
//#include "compiler.h"
#include "pc_pic_cpu.h"
#include <stdio.h>
#include <string.h>


#define Color565(red, green, blue)    (GFX_COLOR) ((((GFX_COLOR)(red) & 0xF8) << 8) | (((GFX_COLOR)(green) & 0xFC) << 3) | (((GFX_COLOR)(blue) & 0xF8) >> 3))
#define ColorBGR(color)    (DWORD) ( ((color & 0xf800) >> 11) | ((color & 0x07e0) << 5) | ((((DWORD)color) & 0x001f) << 16) )
#define ColorRGB(color)    (DWORD) ( ((((DWORD)color) & 0xf800) << 8) | ((((DWORD)color) & 0x07e0) << 5) | ((((DWORD)color) & 0x001f) << 3) )
#define ColorR(color)    ((color & 0xf800) >> 8)        // left-justified, diciamo..
#define ColorG(color)    ((color & 0x07e0) >> 3)
#define ColorB(color)    ((color & 0x001f) << 3)
#define Color565To332(color)    (BYTE) ((WORD)( ((color & 0xe000) >> 8) | ((color & 0x0700) >> 6) | ((color & 0x0018) >> 3) ))
#define Color565To222(color)    (BYTE) ((WORD)( ((color & 0xc000) >> 10) | ((color & 0x0600) >> 7) | ((color & 0x0018) >> 3) ))
//#define Color24To565(color)    ((((color >> 16) & 0xFF) / 8) << 11) | ((((color >> 8) & 0xFF) / 4) << 5) | (((color) &  0xFF) / 8)
  //convert 24bit color into packet 16 bit one (credits for this are all mine) GD made a macro!

#include "breakthrough.h"
#include "breakthrough_private.h"
#include "fat_sd/FSIO.h"
#if defined(USA_USB_HOST_MSD)
#include "../harmony_pic32mz/usb_host_msd.h"
#include "../harmony_pic32mz/usb_host_scsi.h"
#endif
#include "fat_ide/idefsio.h"
#include "superfile.h"

#include "picojpeg.h"
#include "kommissarRexx/kommissarRexx.h"

extern enum FILE_DEVICE m_stdout,m_stdin,m_stderr;
extern const char *ASTERISKS;
extern char prompt[16];


extern volatile unsigned long now;
extern BYTE SDcardOK,USBmemOK,HDOK,FDOK;
extern BYTE *RAMdiscArea;
extern SIZE Screen;
extern DWORD extRAMtot;
extern struct KEYPRESS keypress;
extern struct MOUSE mouse;


const GFX_COLOR standardIcon[]={  // una specie di mela
  BLACK,BLACK,BLACK,GRAY064,LIGHTGREEN,BRIGHTGREEN,GRAY064,BLACK,
  BLACK,BLACK,GRAY064,LIGHTGREEN,GRAY064,BLACK,BLACK,BLACK,
  BLACK,GRAY064,LIGHTRED,LIGHTRED,LIGHTRED,LIGHTRED,GRAY064,BLACK,
  BLACK,GRAY064,LIGHTRED,LIGHTRED,LIGHTRED,LIGHTRED,GRAY064,BLACK,
  BLACK,LIGHTRED,LIGHTRED,BRIGHTRED,BRIGHTRED,LIGHTRED,LIGHTRED,BLACK,
  BLACK,LIGHTRED,LIGHTRED,LIGHTRED,LIGHTRED,LIGHTRED,LIGHTRED,BLACK,
  BLACK,GRAY064,LIGHTRED,LIGHTRED,LIGHTRED,LIGHTRED,GRAY064,BLACK,
  BLACK,BLACK,GRAY064,LIGHTRED,LIGHTRED,GRAY064,BLACK,BLACK,
  };
#define CUR_INV 3
#define CUR_WHT WHITE     //2
#define CUR_BLK BLACK +1 /*+1 se usata trasparenza*/    //1
#define CUR_TRNSP BLACK   //  0 
const GFX_COLOR /*BYTE */standardCursor[]={
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT
  };
const GFX_COLOR standardCursorSm[]={
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT
  };
const GFX_COLOR hourglassCursorSm[]={
  CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP
  };
const GFX_COLOR halfSquareCursor[]={
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP
  };
const GFX_COLOR halfSquareCursorSm[]={
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  };
const GFX_COLOR crossCursorSm[]={
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_WHT,CUR_WHT,CUR_WHT,      CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,
  CUR_WHT,CUR_WHT,CUR_WHT,      CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,CUR_WHT,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_WHT,CUR_WHT,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  };
const GFX_COLOR standardCaret[]={
  BLACK,WHITE /*BLACK*/,BLACK,WHITE /*CUR_TRNSP*/,
  CUR_TRNSP,BLACK,WHITE,CUR_TRNSP,
  CUR_TRNSP,BLACK,WHITE,CUR_TRNSP,
  CUR_TRNSP,BLACK,WHITE,CUR_TRNSP,
  CUR_TRNSP,BLACK,WHITE,CUR_TRNSP,
  CUR_TRNSP,BLACK,WHITE,CUR_TRNSP,
  BLACK,WHITE /*BLACK*/,BLACK,WHITE /*CUR_TRNSP*/,
  CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,CUR_TRNSP,
  };
const GFX_COLOR redBallIcon[]={   //https://www.digole.com/tools/PicturetoC_Hex_converter.php
  BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
  BLACK,0x2110,0xa989,LIGHTMAGENTA,LIGHTMAGENTA,0xa989,0x2110,BLACK,
  BLACK,0xa989,LIGHTMAGENTA,LIGHTMAGENTA,0x09f0,RED,RED,BLACK,
  BLACK,BRIGHTRED,BRIGHTRED,0xd4fa,RED,RED,RED,BLACK,
  BLACK,BRIGHTRED,0x07d0,RED,RED,RED,RED,BLACK,
  BLACK,0xa981,RED,RED,RED,RED,RED,BLACK,
  BLACK,0x2110,RED,RED,RED,RED,0x0008,BLACK,
  BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK
  };
const GFX_COLOR recyclerIcon[]={
  BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
  BLACK,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,BLACK,
  BLACK,LIGHTBLUE,BLACK,BLACK,BLACK,BLACK,LIGHTBLUE,BLACK,
  BLACK,LIGHTBLUE,BLACK,BLACK,BLACK,BLACK,LIGHTBLUE,BLACK,
  BLACK,BLACK,LIGHTBLUE,BLACK,BLACK,LIGHTBLUE,BLACK,BLACK,
  BLACK,BLACK,LIGHTBLUE,BLACK,BLACK,LIGHTBLUE,BLACK,BLACK,
  BLACK,BLACK,BLACK,LIGHTBLUE,LIGHTBLUE,BLACK,BLACK,BLACK,
  BLACK,BLACK,BLACK,LIGHTBLUE,LIGHTBLUE,BLACK,BLACK,BLACK
  };
const GFX_COLOR folderIcon8[]={
  BROWN,BROWN,      BROWN,      SIENNA,       DARKGRAY,       DARKGRAY,       DARKGRAY,       DARKGRAY,
  BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,      SIENNA,       DARKGRAY,       DARKGRAY,       DARKGRAY,
  BROWN,BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      SIENNA,
  BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,
  BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,
  BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,
  BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,
  SIENNA, BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      SIENNA
  };
const GFX_COLOR fileIcon8[]={
  DARKGRAY,WHITE,    WHITE,    WHITE,    WHITE,    WHITE,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     CYAN,     CYAN,    WHITE,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,    WHITE,    WHITE,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     CYAN,     CYAN,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,    WHITE,    WHITE,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     WHITE,     WHITE,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     CYAN,     CYAN,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,    WHITE,    WHITE,    WHITE,    WHITE,   WHITE,DARKGRAY
  };
const GFX_COLOR diskIcon8[]={
  DARKGRAY,WHITE,    WHITE,    WHITE,    WHITE,    WHITE,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     CYAN,     CYAN,    WHITE,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,    WHITE,    WHITE,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     CYAN,     CYAN,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,    WHITE,    WHITE,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     WHITE,     WHITE,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,     CYAN,     CYAN,     CYAN,     CYAN,   WHITE,DARKGRAY,
  DARKGRAY,WHITE,    WHITE,    WHITE,    WHITE,    WHITE,   WHITE,DARKGRAY
  };
const GFX_COLOR folderIcon[]={
  BROWN,BROWN,BROWN, BROWN,BROWN,BROWN,      SIENNA,SIENNA,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,
  BROWN,BROWN,BROWN, BROWN,BROWN,BROWN,      SIENNA,SIENNA,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,      SIENNA,SIENNA,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,      SIENNA,SIENNA,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,       DARKGRAY,DARKGRAY,
  BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      SIENNA,SIENNA,
  BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      SIENNA,SIENNA,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  BROWN,BROWN,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BRIGHTYELLOW,BROWN,BROWN,
  SIENNA, SIENNA, BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      SIENNA,      SIENNA,
  SIENNA, SIENNA, BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      BROWN,      SIENNA,      SIENNA
  };
const GFX_COLOR fileIcon[]={
  DARKGRAY,DARKGRAY,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,WHITE,CYAN, WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,WHITE,WHITE,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,WHITE,WHITE,WHITE,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,WHITE,CYAN, WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,WHITE,WHITE,CYAN,CYAN,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN, CYAN, WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN, CYAN, WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DARKGRAY,DARKGRAY
  };
const GFX_COLOR diskIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,CYAN, BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,CYAN, CYAN, BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,CYAN, WHITE,WHITE,CYAN ,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,CYAN, WHITE,WHITE,CYAN, BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,CYAN, WHITE,WHITE,CYAN, BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,CYAN, CYAN, BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,CYAN, CYAN ,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,CYAN, CYAN, BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,DARKGRAY,
  DARKGRAY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,CYAN, CYAN, BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,DARKGRAY,
  DARKGRAY,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY
  };
const GFX_COLOR networkIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,CYAN,    LIGHTCYAN,LIGHTCYAN,LIGHTCYAN,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,LIGHTCYAN,DARKGRAY,DARKGRAY,DARKGRAY,LIGHTCYAN,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,CYAN,  DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,CYAN    ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,LIGHTCYAN,DARKGRAY,DARKGRAY,DARKGRAY,LIGHTCYAN,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,LIGHTCYAN, DARKGRAY,DARKGRAY,LIGHTCYAN,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,LIGHTCYAN,LIGHTCYAN,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY
  };
const GFX_COLOR printerIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   GRAY192 ,GRAY192 ,GRAY192 ,GRAY192 ,GRAY192 ,GRAY192 ,GRAY192 ,GRAY192 ,GRAY192 ,GRAY192 ,GRAY128, WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,LIGHTRED,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,LIGHTRED,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE   ,WHITE   ,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY
  };
const GFX_COLOR deviceIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY
  };
const GFX_COLOR keyboardIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    LIGHTORANGE,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,LIGHTORANGE,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,LIGHTORANGE,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    LIGHTORANGE,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    LIGHTORANGE,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,LIGHTORANGE,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,PERU,    DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,
  DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY
  };
const GFX_COLOR mouseIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,LIGHTGRAY,LIGHTGRAY,DARKGRAY,WHITE, DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,LIGHTGRAY,LIGHTGRAY,DARKGRAY,WHITE, DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE   ,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   DARKGRAY,DARKGRAY,WHITE   ,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  };
const GFX_COLOR audioIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,GRAY224, DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   GRAY224, DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   YELLOW , YELLOW , WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   YELLOW , YELLOW , WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  };
const GFX_COLOR videoIcon[]={
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,GRAY192, WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   GRAY192,   DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   LIGHTBLUE,WHITE   ,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE   ,LIGHTBLUE,LIGHTBLUE,WHITE,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,GRAY192 ,WHITE,   LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE   ,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   LIGHTBLUE,LIGHTBLUE,WHITE   ,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE,GRAY192, DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,LIGHTBLUE,WHITE,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,MAGENTA, DARKGRAY,SIENNA,  DARKGRAY,YELLOW,  YELLOW,  DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY,
  DARKGRAY,DARKGRAY,WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   WHITE,   DARKGRAY,DARKGRAY,DARKGRAY,DARKGRAY
  };
const GFX_COLOR windowIcon[]={
  GRAY95,GRAY95,GRAY95,GRAY95,GRAY95,GRAY95,GRAY95,GRAY95,
  GRAY95,GRAY2,GRAY2,GRAY2,GRAY2,GRAY2,GRAY2,GRAY95,
  GRAY95,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GRAY95,
  GRAY95,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GRAY95,
  GRAY95,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GRAY95,
  GRAY95,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GRAY95,
  GRAY95,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GRAY95,
  GRAY95,GRAY95,GRAY95,GRAY95,GRAY95,GRAY95,GRAY95,GRAY95
  };

const GFX_COLOR surfWaitIcon[]={
  GRAY096,GRAY096,WHITE,WHITE,WHITE,WHITE,GRAY096,GRAY096,
  GRAY096,GRAY096,WHITE,WHITE,GRAY096,WHITE,GRAY096,GRAY096,
  GRAY096,GRAY096,WHITE,GRAY096,GRAY096,WHITE,GRAY096,GRAY096,
  GRAY096,GRAY096,GRAY096,WHITE,WHITE,GRAY096,GRAY096,GRAY096,
  GRAY096,GRAY096,GRAY096,WHITE,WHITE,GRAY096,GRAY096,GRAY096,
  GRAY096,GRAY096,WHITE,GRAY096,GRAY096,WHITE,GRAY096,GRAY096,
  GRAY096,GRAY096,WHITE,GRAY096,WHITE,WHITE,GRAY096,GRAY096,
  GRAY096,GRAY096,WHITE,WHITE,WHITE,WHITE,GRAY096,GRAY096
  };

const GFX_COLOR speakerIcon[]={
  GRAY096,GRAY096,GRAY096,LIGHTYELLOW,LIGHTYELLOW,GRAY096,GRAY096,GRAY096,
  GRAY096,GRAY096,LIGHTYELLOW,GRAY192,LIGHTYELLOW,GRAY096,BRIGHTYELLOW,GRAY096,
  GRAY096,LIGHTYELLOW,GRAY192,GRAY192,LIGHTYELLOW,BRIGHTYELLOW,GRAY096,GRAY096,
  GRAY096,LIGHTYELLOW,YELLOW,YELLOW,LIGHTYELLOW,GRAY096,YELLOW,GRAY096,
  GRAY096,LIGHTYELLOW,YELLOW,YELLOW,LIGHTYELLOW,GRAY096,YELLOW,GRAY096,
  GRAY096,LIGHTYELLOW,GRAY192,GRAY192,LIGHTYELLOW,BRIGHTYELLOW,GRAY096,GRAY096,
  GRAY096,GRAY096,LIGHTYELLOW,GRAY192,LIGHTYELLOW,GRAY096,BRIGHTYELLOW,GRAY096,
  GRAY096,GRAY096,GRAY096,LIGHTYELLOW,LIGHTYELLOW,GRAY096,GRAY096,GRAY096,
  };


const MENU systemMenu={{   // MF_SYSMENU mettere? dove?
  {"&Ripristina", SC_RESTORE, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Sposta", SC_MOVE, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"R&idimensiona", SC_SIZE, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Ri&duci a icona", SC_MINIMIZE, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Ingrandisci", SC_MAXIMIZE, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Chiudi", SC_CLOSE, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},   // se CS_NOCLOSE deve sparire!
  {"\0\0\0\0", 0, 0, NULL}
  },
  {
  {0}
  }
  };
const MENU systemMenu2={{   // 
  {"&Scroll here", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"&Top", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Bottom", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Page &up", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Page &down", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Scroll up", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Scroll down", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
// MNS_NOTIFYBYPOS v., volendo
const MENU explorerMenu3={{
  {"Dischi", 32, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"A:", 32+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"C:", 32+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
#if defined(USA_USB_HOST_MSD)
  {"E:", 32+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
#endif
#ifdef USA_RAM_DISK 
  {"R:", 32+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
#endif
  {"\0\0\0\0", 0, 0, NULL},{0}
  },
  {
  {'0',0b00000001},{'A',0b00000001},{'C',0b00000001},{'E',0b00000001},{'R',0b00000001},
  }
  };
const MENU explorerMenu1={{
  {"Apri", 1, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&explorerMenu3},
  {"Copia...", 2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Rinomina...", 3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Formatta", 4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Altro", 5, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Esci", 6, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU explorerMenu2={{
  {"Icone &grandi", 16+1, MF_ENABLED | MF_STRING | MF_CHECKED, NULL},
  {"Icone &piccole", 16+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Dettagli", 16+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"&Aggiorna", 16+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0},{0},{0},{0},{0xA5 /*F5*/,0b00000000},
  }
  };
const MENU explorerMenu={{    // il titolo :)
  {"&File", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&explorerMenu1},
  {"&Visualizza", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&explorerMenu2},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU menuControlPanel1={{
  {"&Dischi", 1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Stampanti", 2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Rete", 3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Tastiera", 4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Mouse", 5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Sc&hermo", 6, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Font", 7, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Audio", 8, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"D&ispositivi", 9, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Main", 10, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU menuControlPanel={{    // questo è un popup!
  {"&Sezioni", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&menuControlPanel1},
  {"&Aggiorna", 16, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0},{0xA5 /*F5*/,0b00000000},
  }
  };
const MENU menuStart2={{    // anche questo è un popup!
  {"&Always on top", 17, MF_ENABLED | MF_STRING | MF_CHECKED /*MF_UNCHECKED*/, NULL},
  {"&Orologio", 19, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Mostra desktop", 18, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU menuStart={{    // questo è un popup!
  {"File manager", 1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"MiniBASIC", 8, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Surf!", 9, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Pannello ctrl", 2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Task manager", 3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Calcolatrice", 4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Orologio", 5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Calendario", 10, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Esegui...", 6, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Fine sessione", 7, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU cmdShellMenu1={{
  {"Esegui...", 1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Esci", 2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},{0}
  },
  {
  {'E',0b00000001}
  }
  };
const MENU cmdShellMenu2={{
  {"Cut", 16+1, MF_GRAYED | MF_STRING | MF_CHECKED, NULL},
  {"Copy", 16+2, MF_GRAYED | MF_STRING | MF_CHECKED, NULL},
  {"Paste", 16+3, MF_GRAYED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {'X',0b00000001},{'C',0b00000001},{'V',0b00000001}
  }
  };
const MENU cmdShellMenu={{    // il titolo :)
  {"&File", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&cmdShellMenu1},
  {"&Modifica", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&cmdShellMenu2},
  {"\0\0\0\0", 0, 0, NULL},{0}
  },
  {
  {0}
  }
  };



DLGITEMTEMPLATE fileChooserDlgDlgItem4={MAKECLASS(WC_BUTTON),
  BS_PUSHBUTTON | WS_BORDER | WS_VISIBLE | WS_CHILD | WS_TABSTOP,
  165,82,46,10,
  "Annulla",
  4};
DLGITEMTEMPLATE fileChooserDlgDlgItem3={MAKECLASS(WC_BUTTON),
  BS_DEFPUSHBUTTON | WS_BORDER | WS_VISIBLE | WS_CHILD | WS_TABSTOP,
  140,82,20,10,
  "OK",
  3};
DLGITEMTEMPLATE fileChooserDlgDlgItem2={MAKECLASS(WC_EDIT),
  WS_BORDER | WS_VISIBLE | WS_CHILD | WS_TABSTOP,
  40,82,90,10,
  "*.*",
  2};
DLGITEMTEMPLATE fileChooserDlgDlgItem1={MAKECLASS(WC_STATIC),
  SS_LEFT | WS_BORDER | WS_VISIBLE | WS_CHILD,
  4,82,32,10,
  "File:",
  1};
DLGTEMPLATE fileChooserDlg={WS_BORDER | WS_VISIBLE | WS_DLGFRAME | WS_CAPTION | 
  WS_CHILD | WS_CLIPCHILDREN,
  4,
  15,10,220,100,
  {NULL},
  "Scegli file",
  {&fileChooserDlgDlgItem1,&fileChooserDlgDlgItem2,&fileChooserDlgDlgItem3,&fileChooserDlgDlgItem4}};



const GFX_COLOR surfIcon[]={  // una specie di timone
  BLACK,BLACK,GRAY064,LIGHTYELLOW,GRAY064,BLACK,BLACK,BLACK,
  BLACK,LIGHTYELLOW,GRAY064,LIGHTGREEN,GRAY064,LIGHTYELLOW,BLACK,BLACK,
  BLACK,GRAY064,LIGHTGREEN,GREEN,GREEN,LIGHTGREEN,GRAY064,BLACK,
  LIGHTYELLOW,GRAY064,LIGHTGREEN,LIGHTYELLOW,LIGHTGREEN,GRAY064,LIGHTYELLOW,BLACK,
  LIGHTYELLOW,GRAY064,LIGHTGREEN,LIGHTYELLOW,LIGHTGREEN,GRAY064,LIGHTYELLOW,BLACK,
  BLACK,GRAY064,LIGHTGREEN,GREEN,GREEN,LIGHTGREEN,BLACK,BLACK,
  BLACK,LIGHTYELLOW,GRAY064,LIGHTGREEN,GRAY064,LIGHTYELLOW,BLACK,BLACK,
  BLACK,BLACK,GRAY064,LIGHTYELLOW,GRAY064,BLACK,BLACK,BLACK,
  };

const MENU surfMenu9={{
  {"Argomenti guida", 128+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Inf. su Surf!", 128+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Inf. plug-in", 128+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Note release", 128+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU surfMenu8={{
  {"Nuova finestra", 112+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Sovrapponi", 112+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Affianca", 112+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Disponi icone", 112+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Dividi", 112+5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU surfMenu7={{
  {"Segnalibri", 96+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Casa &ADPM", 96+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"&Google", 96+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Novità", 96+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Cose interesse", 96+5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU surfMenu6={{
  {"Impost. generali", 80+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Impost. rete", 80+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Imp. sicurezza", 80+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Barra strumenti", 80+5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Barra di stato", 80+6, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Barra indirizzi", 80+7, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0}
  }
  };
const MENU surfMenu5={{
  {"Agg. segnalibro", 64+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Apri segnalibri", 64+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {'D',0b00000001},{'B',0b00000001}
  }
  };
const MENU surfMenu4={{
  {"Indietro", 48+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Avanti", 48+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Pagina iniziale", 48+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Stop upload", 48+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Loc. upload", 48+5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0,0b00000000},{0,0b00000000},{0,0b00000000},{0x1b,0b00000000}    // mettere frecce...
  }
  };
const MENU surfMenu3={{
  {"Rileggi", 32+1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Rileggi frame", 32+2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Carica immagini", 32+3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Aggiorna", 32+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"HTML", 32+5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Inf. documento", 32+6, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {0xa5,0 /*anche CTRL-R*/}
  }
  };
const MENU surfMenu2={{
  {"Taglia", 16+1, MF_GRAYED | MF_STRING | MF_UNCHECKED, NULL},
  {"Copia", 16+2, MF_GRAYED | MF_STRING | MF_UNCHECKED, NULL},
  {"Incolla", 16+3, MF_GRAYED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Trova", 16+4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},   // in effetti attivo dopo load document
  {"Ripeti trova", 16+5, MF_GRAYED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Seleziona tutto", 16+6, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {'X',0b00000001},{'C',0b00000001},{'V',0b00000001}
  }
  };
const MENU surfMenu1={{
  {"Nuovo browser", 1, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Apri URL...", 2, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Apri file...", 3, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Salva...", 4, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, MF_SEPARATOR, NULL},
  {"Stampa...", 5, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"Imp. stampante", 6, MF_ENABLED | MF_STRING | MF_UNCHECKED, NULL},
  {"\0\0\0\0", 0, 0, NULL},
  },
  {
  {'N',0b00000001},{'O',0b00000001}
  }
  };
const MENU surfMenu={{    // il titolo :)
  {"&File", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu1},
  {"&Modifica", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu2},
  {"&Vista", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu3},
  {"V&ai", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu4},
  {"&Segnalibri", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu5},
  {"&Opzioni", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu6},
  {"&Directory", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu7},
  {"&Finestra", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu8},
  {"&?", 0, MF_ENABLED | MF_STRING | MF_UNCHECKED | MF_POPUP, (MENU*)&surfMenu9},
  {"\0\0\0\0", 0, 0, NULL},{0}
  },
  {
  {0}
  }
  };

